name: pysocketstream
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pylint pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint -E pysocketstream
      #    - name: Test with pytest
      #      run: |
      #        python tests/testsuite.py
      # - name: Generate coverage report
      #   run: |
      #     pytest --cov=pysocketstream --cov-report=xml
      # - name: "Upload coverage to Codecov"
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true
